### ISSUE TITLE
Add troubleshooting section

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#1100]
Sometimes checkers fail, but all our manual has to offer is [this poor section](http://www.flycheck.org/en/latest/user/syntax-checks.html#debug-syntax-checking) that I came up with.  That's too little.

Let's expand that to a proper "troubleshooting" top-level section of the user guide that mentions this command as well as `C-c ! C-c`, and gives a general guide line on how to troubleshoot Flycheck syntax checkers.

# TODO

- [x] Add troubleshooting section, documenting `C-c ! v` and `C-c ! C-c`
- [x] Suggest to update the syntax checker if it fails with unknown flags, see #1108
- [x] For OS X users, refer to exec-path-from-shell, also in the "try out section", the quickstart guide, and the installation instructions
- [x] Prominently link in the "try out section" on the front page, in the quickstart guide and after the installation instructions

**Comment by fmdkdd** [comment]
Given the recent influx of issues where users had to first set up their path properly, this could definitely help.

**Comment by lunaryorn** [comment]
@fmdkdd Great point, we should definitely refer to exec-path-from-shell here.
