### ISSUE TITLE
Track error IDs

### ISSUE THREAD

**Issue by swsnr** [flycheck/flycheck#529]
Track error IDs in a separate field of `flycheck-error`, to improve support for identifying errors unambiguously.

Currently Flycheck does not know about error IDs.  Some syntax checkers store them as part of the error message (e.g. Shellcheck `Use $(..) instead of deprecated`..`[SC2006]`).

Add a separate `id` field to the `flycheck-error` object, and an `rx` form to parse error IDs into the `id` field.  Also extend the existing error parsers, and update all syntax checkers to extract IDs where possible.
# Syntax checkers with IDs
- [x] Shellcheck (use checkstyle parsing again)
- [x] jshint
- [x] csslint
- [x] Pylint
- [x] Flake8
- [x] Chktex
- [x] Rubocop
- [x] phpmd (we need to parse its xml for this)
- [x] perlcritic
- [x] cppcheck
# TODOs
- [x] Extract error IDs from syntax checkers
- [x] Update the error list to include error ids
- [x] Include error ids in error display
- [x] Copy error ids into kill ring
- [ ] Google for error ids
