### ISSUE TITLE
Add Gitter chatroom

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#820]
Once #819 is done, open a Gitter chatroom for Flycheck. Follow up from #796.

## TODO

- [ ] Open a public channel for flycheck/flycheck
- [ ] Open an internal channel for the organization
- [ ] Open an internal channel for maintainers and leads only
- [ ] Check how to link the code of conduct in the channel
- [ ] Add a README badge for the public channel
- [ ] Add Github integration for public channel
- [ ] Add Travis CI integration for public channel, for builds of flycheck and flycheck.github.io

**Comment by lunaryorn** [comment]
I forgot to say that I setup the flycheck/flycheck Gitter channel for all our users to join.

**Comment by cpitclaudel** [comment]
Cool :)
