### ISSUE TITLE
Make rake verify:elisp fail on checkdoc warnings

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#843]
Currently checkdoc dumps a lot of warnings that we should fix or ignore so that `rake verify:elisp` is clean.

Subsequently we should make `rake verify:elisp` fail if there are any warnings, as checkdoc failures should cause Travis CI to fail.

## Tasks

- [x] Move `flycheck-checkdoc.el` from `test/` to `admin/` where it belongs
- [x] Fix checkdoc warnings that can be fixed
- [x] Post-process checkdoc output  in `rake verify:elisp` to suppress warnings that are false positives
- [x] Make `rake verify:checkdoc` fail if there's any checkdoc output

## Related work 

Also use this opportunity to turn the code style tests (untabified and intended) into `rake verify:elisp` components:

- [x] Write Ruby code to search for tabs, and output line:column:message if there's a tab somewhere
- [ ] Run the "indentation" test directly from Rake and output a unified diff if the indentation was not correct.

That should allow better debugging of code style violations, and moves something that should never have been a test in the first place to the right location.

**Comment by lunaryorn** [comment]
Waiting for #840
