### ISSUE TITLE
Add usage section to manual

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#927]
## TODO

- [x] Add installation instructions
- [x] Add quickstart section
- [x] Checking buffers
- [x] Syntax checkers
- [x] Reporting results
- [x] Error navigation
- [x] Error display
- [x] Error killing
- [x] Error list
- [x] Mode line display
- [x] Configuring checkers
